# Generated by Django 3.0.3 on 2020-02-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.IntegerField(verbose_name='National Phone Number'),
        ),
    ]
