# Generated by Django 3.0.3 on 2020-02-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200217_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='a', max_length=15, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='a', max_length=15, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
