# Generated by Django 3.0.3 on 2020-02-19 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200217_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_login_time', models.DateTimeField(default=datetime.datetime(2020, 2, 19, 20, 25, 1, 274763, tzinfo=utc), verbose_name='Login Time')),
                ('_logout_time', models.DateTimeField(verbose_name='Logout Time')),
                ('_duration_hours', models.DurationField(verbose_name='Duration (Hours)')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff')),
            ],
        ),
    ]
