# Generated by Django 3.0.3 on 2020-03-17 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sessionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioneventmodel',
            name='_logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Logout Time'),
        ),
    ]
