# Generated by Django 3.0.3 on 2020-04-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200317_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('creator_id', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authoriser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Staff')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Role')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff')),
            ],
            options={
                'unique_together': {('staff_id', 'role_id')},
            },
        ),
        migrations.CreateModel(
            name='RolesApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.App')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Role')),
            ],
            options={
                'unique_together': {('role_id', 'app_id')},
            },
        ),
    ]
