# Generated by Django 3.0.3 on 2020-04-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_app_role_rolesapp_staffrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Staff'),
        ),
    ]
