# Generated by Django 3.0.3 on 2020-05-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200403_1513'),
        ('inventory', '0004_auto_20200403_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('total', models.FloatField(verbose_name='Total (£)')),
                ('completed', models.BooleanField()),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Staff')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price (£)'),
        ),
        migrations.CreateModel(
            name='TransactionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField(verbose_name='Subtotal (£)')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Transaction')),
            ],
        ),
    ]
