# Generated by Django 3.0.3 on 2020-05-12 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200512_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 12, 14, 59, 19, 921808, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category'),
        ),
    ]
